CREATE DATABASE order_db;
CREATE DATABASE inventory_db;
CREATE DATABASE payment_db;
CREATE DATABASE analytics_db;
CREATE DATABASE auth_db;
CREATE DATABASE keycloak_db;

-- Grant permissions
GRANT ALL PRIVILEGES ON DATABASE order_db TO "user";
GRANT ALL PRIVILEGES ON DATABASE inventory_db TO "user";
GRANT ALL PRIVILEGES ON DATABASE payment_db TO "user";
GRANT ALL PRIVILEGES ON DATABASE analytics_db TO "user";
GRANT ALL PRIVILEGES ON DATABASE auth_db TO "user";
GRANT ALL PRIVILEGES ON DATABASE keycloak_db TO "user";
